sudo: false
language: python
python:
  - 2.7

cache:
  # must specify pip dir
  # https://github.com/travis-ci/travis-ci/issues/3239
  directories:
    - $HOME/virtualenv
    - $HOME/.cache/pip

env:
  global:
    # These two environment variables could be set by Travis itself, or Travis
    # could configure itself in /etc/, ~/, or inside of the virtual
    # environments. In any case if these two values get configured then end
    # users only need to enable the pip cache and manually run pip wheel before
    # running pip install.
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

before_install:
  - pip install -U pip
  - pip install check-manifest readme_renderer flake8 docutils
  - dev/install_pysqlite.sh

install:
  - pip install -U -e .

script:
  - python setup.py test
  - check-manifest --ignore
    "tox.ini,test*,devtools*,docs*,taxtastic/data,taxtastic/data/*"
  - python setup.py check --metadata --restructuredtext --strict
  - flake8 taxtastic
