name: Build and push docker image

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  push_to_registry:
    environment: docker_build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            crosenth/taxtastic:latest
            crosenth/taxtastic:${{ env.RELEASE_VERSION }}
