name: Build and push GH-Pages

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  push_gh_pages:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build Sphinx
        run: |
          pip install sphinx
          python setup.py build_sphinx --source-dir docs --build-dir .
      -
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
