name: Run Taxtastic tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fhcrc/taxtastic:latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest
    - run: pytest tests
